### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by culdep-sh** [burkybang/SuiteScript-2.0-WebStorm-File-Templates#1]
[SuiteScript 2.0/ SuiteScript 2.0 / Suitelet Script File.js ](https://github.com/burkybang/SuiteScript-WebStorm-File-Templates/blob/master/SuiteScript%202.0/SuiteScript%202.0%20Suitelet%20Script%20File.js#L42)

there is a comma at the end of the function at line 42.
it should be "}" instead of "},"

**Comment by burkybang** [comment]
Actually it's intended. That's valid JavaScript. It's called a trailing comma. You'll notice the same thing in all of the other 2.x templates.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by culdep-sh** [comment]
sorry, pebkac.
I was getting a error and mistakenly attributed to your code.

**Comment by burkybang** [comment]
No prob! Haha, I had never heard of that acronym. Gave me a chuckle
